# config.yaml
model:
  name: "convnext_tiny"
  learning_rate: 0.001
  batch_size: 4
  epochs: 25
  w_low: 0.07
  w_mdm: 0.18
  w_hgh: 0.75

dataset:
  path: "//catalogue/WFP_ClimateRiskPr1/5.Others/thesis/data/pbi_smpl_categorical"